"""Single source of truth for every path the pipeline reads or writes.

Everything generated by a run lives under one `artifacts/` tree::

    artifacts/
      data/        data.csv, ground_truth.parquet   (the synthetic panel)
      logs/        execution.log
      models/      iforest.joblib, vae_best.pt, vae/, vae_tuning/
      tuning/      optuna_*.db, best_params_*.yaml  (Optuna outputs)
      reports/     anomaly_report.{html,md}, model_documentation.md, oot_top10_*.xlsx, figures/

so the repository root holds only source (``main.py``, ``src/``, ``tests/``,
``docs/``) and the entire generated state can be inspected -- or deleted -- in
one place.

Two properties every value here must keep:

* **Relative, never absolute.** ``tests/conftest.py`` chdirs the whole session
  into a throwaway sandbox precisely so these defaults resolve there and never
  touch the real tree. An absolute path would defeat that.
* **Built with :func:`os.path.join`,** so Windows and POSIX separators are both
  handled by the standard library rather than by string concatenation.

``figures/`` is deliberately flat: figure filenames already carry their
producing module as a prefix (``iforest_*``, ``vae_*``, ``embedding_*``,
``roc_pr_*``), which is enough to group them without a directory per module.
This still satisfies the project-wide rule that *every* figure from *every*
module lands under one figures directory.
"""

from __future__ import annotations

import os

__all__ = [
    "ARTIFACTS_DIR",
    "DATA_DIR",
    "LOGS_DIR",
    "MODELS_DIR",
    "TUNING_DIR",
    "REPORTS_DIR",
    "FIGURES_DIR",
    "DATA_PATH",
    "GROUND_TRUTH_PATH",
    "LOG_FILE",
    "IFOREST_MODEL",
    "VAE_MODEL",
    "VAE_DETECTOR",
    "VAE_CHECKPOINT_DIR",
    "VAE_TUNING_CHECKPOINT_DIR",
    "IFOREST_STUDY_DB",
    "VAE_STUDY_DB",
    "IFOREST_BEST_PARAMS",
    "VAE_BEST_PARAMS",
    "OOT_REPORT_DEFAULT",
    "RUN_EVENTS_LOG",
    "FLOW_VISUALIZATION_DEFAULT",
]

# -- roots ------------------------------------------------------------------ #
ARTIFACTS_DIR = "artifacts"

DATA_DIR = os.path.join(ARTIFACTS_DIR, "data")
LOGS_DIR = os.path.join(ARTIFACTS_DIR, "logs")
MODELS_DIR = os.path.join(ARTIFACTS_DIR, "models")
# Optuna outputs (study databases + best-params YAML). Named "tuning" rather
# than "configs" because nothing here is input configuration -- every file is
# written by `tune_iforest` / `tune_vae`.
TUNING_DIR = os.path.join(ARTIFACTS_DIR, "tuning")
REPORTS_DIR = os.path.join(ARTIFACTS_DIR, "reports")
FIGURES_DIR = os.path.join(REPORTS_DIR, "figures")

# -- data ------------------------------------------------------------------- #
DATA_PATH = os.path.join(DATA_DIR, "data.csv")
GROUND_TRUTH_PATH = os.path.join(DATA_DIR, "ground_truth.parquet")

# -- logging ---------------------------------------------------------------- #
LOG_FILE = "execution.log"

# -- model artifacts -------------------------------------------------------- #
IFOREST_MODEL = os.path.join(MODELS_DIR, "iforest.joblib")
VAE_MODEL = os.path.join(MODELS_DIR, "vae_best.pt")
VAE_DETECTOR = os.path.join(MODELS_DIR, "vae.pt")
VAE_CHECKPOINT_DIR = os.path.join(MODELS_DIR, "vae")
# One subdirectory per Optuna trial, for crash-resume during tuning. Transient:
# safe to delete once a study has finished (see .gitignore).
VAE_TUNING_CHECKPOINT_DIR = os.path.join(MODELS_DIR, "vae_tuning")

# -- tuning artifacts ------------------------------------------------------- #
IFOREST_STUDY_DB = os.path.join(TUNING_DIR, "optuna_iforest.db")
VAE_STUDY_DB = os.path.join(TUNING_DIR, "optuna_vae.db")
IFOREST_BEST_PARAMS = os.path.join(TUNING_DIR, "best_params_iforest.yaml")
VAE_BEST_PARAMS = os.path.join(TUNING_DIR, "best_params_vae.yaml")

# -- reports ---------------------------------------------------------------- #
OOT_REPORT_DEFAULT = os.path.join(REPORTS_DIR, "oot_top_anomalies.xlsx")
FLOW_VISUALIZATION_DEFAULT = os.path.join(REPORTS_DIR, "flow_visualization.html")

# -- observability ------------------------------------------------------------ #
# Structured JSON-Lines event stream (src/utils/observability.py); the source
# `src.reporting.flow_visualization` reads to render the flow diagram above.
RUN_EVENTS_LOG = os.path.join(LOGS_DIR, "run_events.jsonl")
