"""Single source of truth for every path the pipeline reads or writes.

Everything generated by a run lives under one `artifacts/` tree::

    artifacts/
      data/        data.csv, ground_truth.parquet   (the synthetic panel)
      logs/        execution.log
      models/      iforest.joblib, vae_best.pt, vae/, vae_tuning/
      tuning/      optuna_*.db, best_params_*.yaml  (Optuna outputs)
      reports/     anomaly_report.{html,md}, model_documentation.md, oot_top10_*.xlsx, figures/

so the repository root holds only source (``main.py``, ``src/``, ``tests/``,
``docs/``) and the entire generated state can be inspected -- or deleted -- in
one place.

Two properties every value here must keep:

* **Relative, never absolute.** ``tests/conftest.py`` chdirs the whole session
  into a throwaway sandbox precisely so these defaults resolve there and never
  touch the real tree. An absolute path would defeat that.
* **Built with :func:`os.path.join`,** so Windows and POSIX separators are both
  handled by the standard library rather than by string concatenation.

``figures/`` is deliberately flat: figure filenames already carry their
producing module as a prefix (``iforest_*``, ``vae_*``, ``embedding_*``,
``roc_pr_*``), which is enough to group them without a directory per module.
This still satisfies the project-wide rule that *every* figure from *every*
module lands under one figures directory.
"""

from __future__ import annotations

import os

__all__ = [
    "ARTIFACTS_DIR",
    "DATA_DIR",
    "LOGS_DIR",
    "MODELS_DIR",
    "TUNING_DIR",
    "REPORTS_DIR",
    "FIGURES_DIR",
    "DATA_PATH",
    "GROUND_TRUTH_PATH",
    "SYNTHETIC_MARKER_SUFFIX",
    "synthetic_marker_for",
    "DEV_SEGMENT",
    "dev_variant",
    "LOG_FILE",
    "IFOREST_MODEL",
    "VAE_MODEL",
    "VAE_DETECTOR",
    "VAE_CHECKPOINT_DIR",
    "VAE_TUNING_CHECKPOINT_DIR",
    "IFOREST_STUDY_DB",
    "VAE_STUDY_DB",
    "IFOREST_BEST_PARAMS",
    "VAE_BEST_PARAMS",
    "OOT_REPORT_DEFAULT",
    "RUN_EVENTS_LOG",
    "FLOW_VISUALIZATION_DEFAULT",
    "ANALYST_DASHBOARD_DEFAULT",
]

# -- roots ------------------------------------------------------------------ #
ARTIFACTS_DIR = "artifacts"

DATA_DIR = os.path.join(ARTIFACTS_DIR, "data")
LOGS_DIR = os.path.join(ARTIFACTS_DIR, "logs")
MODELS_DIR = os.path.join(ARTIFACTS_DIR, "models")
# Optuna outputs (study databases + best-params YAML). Named "tuning" rather
# than "configs" because nothing here is input configuration -- every file is
# written by `tune_iforest` / `tune_vae`.
TUNING_DIR = os.path.join(ARTIFACTS_DIR, "tuning")
REPORTS_DIR = os.path.join(ARTIFACTS_DIR, "reports")
FIGURES_DIR = os.path.join(REPORTS_DIR, "figures")

# -- data ------------------------------------------------------------------- #
DATA_PATH = os.path.join(DATA_DIR, "data.csv")
GROUND_TRUTH_PATH = os.path.join(DATA_DIR, "ground_truth.parquet")

#: Suffix of the provenance marker the synthetic generator drops beside the
#: panel it writes. Its presence is what lets a *later* run still recognise a
#: CSV as generated: without it, the second run onward would load the same
#: synthetic file from disk and be unable to tell it from real data -- and
#: would then persist tuned hyperparameters fitted to invented numbers.
#:
#: Named after the panel (``data.csv`` -> ``data.csv.synthetic.json``) rather
#: than being one marker per directory. A directory-wide marker mislabels a
#: *real* panel dropped into a folder that once held a generated one -- which
#: is the normal way this gets used, since `artifacts/data/` is the default
#: location for both.
SYNTHETIC_MARKER_SUFFIX = ".synthetic.json"


def synthetic_marker_for(data_path: str) -> str:
    """Path of the provenance marker that belongs with ``data_path``."""
    return data_path + SYNTHETIC_MARKER_SUFFIX


#: Subdirectory that holds artifacts from non-official (synthetic-data) runs.
#: Keeping them under a sibling folder rather than suffixing filenames means
#: the official tree can be inspected, shipped or wiped without picking
#: through a mix of real and generated outputs.
DEV_SEGMENT = "_dev"


def dev_variant(path: str) -> str:
    """Redirect ``path`` into the :data:`DEV_SEGMENT` sibling directory.

    ``artifacts/tuning/best_params_vae.yaml`` becomes
    ``artifacts/tuning/_dev/best_params_vae.yaml``.

    Used for every artifact a synthetic run would otherwise write over the
    official one -- tuned parameters, model checkpoints, Optuna studies. A
    model fitted to invented data must not be able to masquerade as the
    deployed one just because it was the last thing written.
    """
    parent, name = os.path.split(path)
    return os.path.join(parent, DEV_SEGMENT, name)

# -- logging ---------------------------------------------------------------- #
LOG_FILE = "execution.log"

# -- model artifacts -------------------------------------------------------- #
IFOREST_MODEL = os.path.join(MODELS_DIR, "iforest.joblib")
VAE_MODEL = os.path.join(MODELS_DIR, "vae_best.pt")
VAE_DETECTOR = os.path.join(MODELS_DIR, "vae.pt")
VAE_CHECKPOINT_DIR = os.path.join(MODELS_DIR, "vae")
# One subdirectory per Optuna trial, for crash-resume during tuning. Transient:
# safe to delete once a study has finished (see .gitignore).
VAE_TUNING_CHECKPOINT_DIR = os.path.join(MODELS_DIR, "vae_tuning")

# -- tuning artifacts ------------------------------------------------------- #
IFOREST_STUDY_DB = os.path.join(TUNING_DIR, "optuna_iforest.db")
VAE_STUDY_DB = os.path.join(TUNING_DIR, "optuna_vae.db")
IFOREST_BEST_PARAMS = os.path.join(TUNING_DIR, "best_params_iforest.yaml")
VAE_BEST_PARAMS = os.path.join(TUNING_DIR, "best_params_vae.yaml")

# -- reports ---------------------------------------------------------------- #
OOT_REPORT_DEFAULT = os.path.join(REPORTS_DIR, "oot_top_anomalies.xlsx")
FLOW_VISUALIZATION_DEFAULT = os.path.join(REPORTS_DIR, "flow_visualization.html")
# `{model}` is filled in by the caller (one dashboard per deliverable model,
# same convention as the OOT Excel's `oot_p90_<model>.xlsx` naming) -- see
# `src/reporting/analyst_dashboard.py`.
ANALYST_DASHBOARD_DEFAULT = os.path.join(REPORTS_DIR, "analyst_dashboard_{model}.html")

# -- observability ------------------------------------------------------------ #
# Structured JSON-Lines event stream (src/utils/observability.py); the source
# `src.reporting.flow_visualization` reads to render the flow diagram above.
RUN_EVENTS_LOG = os.path.join(LOGS_DIR, "run_events.jsonl")
